<database name="default">
  <table name="user" phpName="User">
    <column name="firstName" type="varchar" size="50" required="true" phpName="FirstName"/>
    <column name="lastName" type="varchar" size="50" required="true" phpName="LastName"/>
    <column name="netId" type="varchar" size="24" required="true" phpName="NetID" primaryKey="true"/>
    <column name="email" type="varchar" size="255" required="true" phpName="Email"/>
    </table>
  <table name="class" phpName="Class">
    <column name="classID" type="varchar" size="11" required="true" primaryKey="true" phpName="ClassID" />
    <column name="subject" type="varchar" size="3" required="true" phpName="Subject"/>
    <column name="catalogNumber" type="integer" size="3" required="true" phpName="Category"/>
    <column name="section" type="varchar" size="3" required="true" phpName="Section"/>
    <column name="InstructorNetID" type="varchar" size="128" required="true" phpName="ClassID"/>
  </table>
  <table name="roster" phpName="Roster">
    <column name="classID" type="varchar" size="11" required="true" primaryKey="true"/>
    <column name="subject" type="varchar" size="3" required="true"/>
    <column name="catalogNumber" type="integer" size="3" required="true"/>
    <column name="section" type="varchar" size="3" required="true"/>
    <column name="instructorNetID" type="varchar" size="128" required="true"/>
  </table>
</database>
