/*
 * DATE TABLE- This will hold each date that exists. The date knows what term its in, whether the center is open on its date, and has information for
 * each of its timeslots which represent 30minute intervals in a 24hour day.
 * @timeslotx  - Value = 0 available, 1 = taken. Additional logic must decide whether timeslot is within centers hours.
 */
CREATE TABLE date
(
Date DATE NOT NULL,
Term varchar(4) NOT NULL,
Utilization int (3) NOT NULL default 0,
centerIsOpen bool NOT NULL default TRUE,
timeslot0 int(1) NOT NULL default 0,
timeslot1 int(1) NOT NULL default 0,
timeslot2 int(1) NOT NULL default 0,
timeslot3 int(1) NOT NULL default 0,
timeslot4 int(1) NOT NULL default 0,
timeslot5 int(1) NOT NULL default 0,
timeslot6 int(1) NOT NULL default 0,
timeslot7 int(1) NOT NULL default 0,
timeslot8 int(1) NOT NULL default 0,
timeslot9 int(1) NOT NULL default 0,
timeslot10 int(1) NOT NULL default 0,
timeslot11 int(1) NOT NULL default 0,
timeslot12 int(1) NOT NULL default 0,
timeslot13 int(1) NOT NULL default 0,
timeslot14 int(1) NOT NULL default 0,
timeslot15 int(1) NOT NULL default 0,
timeslot16 int(1) NOT NULL default 0,
timeslot17 int(1) NOT NULL default 0,
timeslot18 int(1) NOT NULL default 0,
timeslot19 int(1) NOT NULL default 0,
timeslot20 int(1) NOT NULL default 0,
timeslot21 int(1) NOT NULL default 0,
timeslot22 int(1) NOT NULL default 0,
timeslot23 int(1) NOT NULL default 0,
timeslot24 int(1) NOT NULL default 0,
timeslot25 int(1) NOT NULL default 0,
timeslot26 int(1) NOT NULL default 0,
timeslot27 int(1) NOT NULL default 0,
timeslot28 int(1) NOT NULL default 0,
timeslot29 int(1) NOT NULL default 0,
timeslot30 int(1) NOT NULL default 0,
timeslot31 int(1) NOT NULL default 0,
timeslot32 int(1) NOT NULL default 0,
timeslot33 int(1) NOT NULL default 0,
timeslot34 int(1) NOT NULL default 0,
timeslot35 int(1) NOT NULL default 0,
timeslot36 int(1) NOT NULL default 0,
timeslot37 int(1) NOT NULL default 0,
timeslot38 int(1) NOT NULL default 0,
timeslot39 int(1) NOT NULL default 0,
timeslot40 int(1) NOT NULL default 0,
timeslot41 int(1) NOT NULL default 0,
timeslot42 int(1) NOT NULL default 0,
timeslot43 int(1) NOT NULL default 0,
timeslot44 int(1) NOT NULL default 0,
timeslot45 int(1) NOT NULL default 0,
timeslot46 int(1) NOT NULL default 0,
timeslot47 int(1) NOT NULL default 0,
timeslot48 int(1) NOT NULL default 0

);
